Repository 1-MSG/backend, pull requests merged in 2024-04, with the labels that each got.

#82 fix : 장바구니 조회 응답값 수정 #74
  src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
  src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :recycle: refactor

#85 feat: 상품 상세 조회 기능 구현
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/entity/ProductImage.java
  src/main/java/spharos/msg/domain/product/entity/ProductInfoDetail.java
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/product/repository/ProductImageRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductSalesInfoRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/entity/Brand.java
Labels: :feather: enhancement

#95 feat: 상품 리뷰 목록 조회 api 구현
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/repository/ProductImageRepository.java
  src/main/java/spharos/msg/domain/review/controller/ReviewController.java
  src/main/java/spharos/msg/domain/review/dto/ReviewResponse.java
  src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java
  src/main/java/spharos/msg/domain/review/service/ReviewService.java
Labels: :feather: enhancement

#87 feat : 카테고리 관련 API 구현 #78
  src/main/java/spharos/msg/domain/category/controller/CategoryController.java
  src/main/java/spharos/msg/domain/category/dto/CategoryResponse.java
  src/main/java/spharos/msg/domain/category/entity/Category.java
  src/main/java/spharos/msg/domain/category/entity/CategoryProduct.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepository.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/category/repository/CategoryRepository.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryService.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/exception/CategoryException.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/test/java/spharos/msg/domain/category/repository/CategoryProductRepositoryTest.java
  src/test/java/spharos/msg/domain/category/service/CategoryServiceTest.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#96 refactor : 검색 결과 조회 API 코드 리팩토링 및 검색 예외 처리 강화 #94
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/main/java/spharos/msg/domain/search/utils/SearchKeywordFinder.java
  src/main/java/spharos/msg/global/api/code/BaseErrorCode.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/api/exception/SearchException.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java
Labels: :recycle: refactor

#99 Revert "refactor : 검색 결과 조회 API 코드 리팩토링 및 검색 예외 처리 강화 #94"
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/main/java/spharos/msg/domain/search/utils/SearchKeywordFinder.java
  src/main/java/spharos/msg/global/api/code/BaseErrorCode.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/api/exception/SearchException.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java
Labels: :x: invalid

#91 feat : 통합 아이디, 간편 아이디 찾기
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/controller/OAuthController.java
  src/main/java/spharos/msg/domain/users/dto/response/FindIdOutDto.java
  src/main/java/spharos/msg/domain/users/repository/UserOAuthListRepository.java
  src/main/java/spharos/msg/domain/users/service/AuthService.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/OAuthService.java
  src/main/java/spharos/msg/domain/users/service/OAuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/UsersService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/SecurityConfiguration.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#100 feat : 검색 결과 조회 API 코드 리팩토링
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
Labels: :bug: bug

#103 feat : Admin 집계용 Table 생성
  src/main/java/spharos/msg/domain/admin/controller/CountPriceController.java
  src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
  src/main/java/spharos/msg/domain/admin/entity/CountPrice.java
  src/main/java/spharos/msg/domain/admin/entity/CountUser.java
  src/main/java/spharos/msg/domain/admin/repository/CountPriceRepository.java
  src/main/java/spharos/msg/domain/admin/repository/CountUserRepository.java
  src/main/java/spharos/msg/domain/admin/service/CountPriceService.java
  src/main/java/spharos/msg/domain/admin/service/CountUserService.java
Labels: :feather: enhancement

#105 feat : option테이블 DB구조 수정 #83
  src/main/java/spharos/msg/domain/cart/dto/CartProductOptionResponseDto.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/dto/OptionsTypeDto.java
  src/main/java/spharos/msg/domain/options/entity/Options.java
  src/main/java/spharos/msg/domain/options/repository/OptionsRepository.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
  src/main/java/spharos/msg/domain/product/controller/ProductOptionController.java
  src/main/java/spharos/msg/domain/product/dto/ProductOptionIdDto.java
  src/main/java/spharos/msg/domain/product/entity/ProductOption.java
  src/main/java/spharos/msg/domain/product/entity/option/OptionColor.java
  src/main/java/spharos/msg/domain/product/entity/option/OptionEtc.java
  src/main/java/spharos/msg/domain/product/entity/option/OptionSize.java
  src/main/java/spharos/msg/domain/product/service/ProductOptionService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement, :recycle: refactor

#101 feat : 사용자 정보 조회/변경/탈퇴
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/users/controller/AddressController.java
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/controller/OAuthController.java
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/dto/request/ChangePasswordRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EasyLoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EasySignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/response/LoginOutDto.java
  src/main/java/spharos/msg/domain/users/dto/response/SearchAddressOutDto.java
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/main/java/spharos/msg/domain/users/repository/UserOAuthListRepository.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/AddressService.java
  src/main/java/spharos/msg/domain/users/service/AuthService.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/OAuthServiceImpl.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#109 feat: 특가 상품 조회 api 구현
  .idea/dataSources.xml
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/bundle/controller/BundleController.java
  src/main/java/spharos/msg/domain/bundle/dto/BundleResponse.java
  src/main/java/spharos/msg/domain/bundle/entity/Bundle.java
  src/main/java/spharos/msg/domain/bundle/entity/BundleProduct.java
  src/main/java/spharos/msg/domain/bundle/repository/BundleProductRepository.java
  src/main/java/spharos/msg/domain/bundle/repository/BundleRepository.java
  src/main/java/spharos/msg/domain/bundle/service/BundleService.java
  src/main/java/spharos/msg/domain/product/entity/ProductInfoDetail.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#113 feat: 카테고리 목록 조회에 "상품 전체보기" 추가 #112
  src/main/java/spharos/msg/domain/category/controller/CategoryController.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryService.java
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/category/repository/CategoryProductRepositoryTest.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#108 feat : 전체 상품 브랜드 조회 #106
  src/main/java/spharos/msg/domain/brand/controller/BrandController.java
  src/main/java/spharos/msg/domain/brand/dto/BrandResponseDto.java
  src/main/java/spharos/msg/domain/brand/entity/Brand.java
  src/main/java/spharos/msg/domain/brand/repository/BrandRepository.java
  src/main/java/spharos/msg/domain/brand/service/BrandService.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#118 RE: PR
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/main/java/spharos/msg/domain/search/utils/KeywordModifier.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/api/exception/SearchException.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java
Labels: :feather: enhancement

#119 feat : Admin용 사용자 정보 조회 (일부 구현)
  src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
  src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
  src/main/java/spharos/msg/domain/admin/entity/CountPrice.java
  src/main/java/spharos/msg/domain/admin/entity/CountUser.java
  src/main/java/spharos/msg/domain/admin/service/CountUserService.java
  src/main/java/spharos/msg/domain/users/controller/AddressController.java
  src/main/java/spharos/msg/domain/users/entity/LoginType.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/OAuthServiceImpl.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/redis/RedisService.java
Labels: :feather: enhancement

#124 bug : refresh Token 재발급 절차 변경.
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
Labels: :bug: bug

#127 feat : MyPage용 회원 정보 조회 API
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/dto/response/FindUserInfoOutDto.java
  src/main/java/spharos/msg/domain/users/service/AuthService.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#129 want : 카테고리 목록 조회 API의 응답값 변경 및 반환값에 parent_id 추가 #128
  src/main/java/spharos/msg/domain/category/controller/CategoryController.java
  src/main/java/spharos/msg/domain/category/dto/CategoryResponse.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryService.java
  src/test/java/spharos/msg/domain/category/repository/CategoryProductRepositoryTest.java
Labels: :hammer_and_pick: want

#123 feat : 상품 주문 API 구현 #121
  src/main/java/spharos/msg/domain/orders/controller/OrderController.java
  src/main/java/spharos/msg/domain/orders/dto/OrderRequest.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/entity/OrderDetail.java
  src/main/java/spharos/msg/domain/orders/entity/OrderProduct.java
  src/main/java/spharos/msg/domain/orders/entity/Orders.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/review/entity/Review.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#126 feat : 장바구니 담기 요청값 변경/옵션 조회 API구현 #114 , #125
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductQuantityDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductRequestDto.java
  src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
  src/main/java/spharos/msg/domain/options/dto/OptionsResponseDto.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
  src/main/java/spharos/msg/domain/product/controller/ProductOptionController.java
  src/main/java/spharos/msg/domain/product/dto/ProductOptionIdDto.java
  src/main/java/spharos/msg/domain/product/service/ProductOptionService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
Labels: :bug: bug, :feather: enhancement, :recycle: refactor

#122 feat: 상품 정보 조회 api 추가 구현
  .idea/dataSources.xml
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/product/repository/impl/ProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#132 refactor : 회원 탈퇴 정책 변경
  src/main/java/spharos/msg/domain/admin/controller/CountPriceController.java
  src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
  src/main/java/spharos/msg/domain/admin/entity/CountPrice.java
  src/main/java/spharos/msg/domain/admin/entity/CountUser.java
  src/main/java/spharos/msg/domain/admin/repository/CountPriceRepository.java
  src/main/java/spharos/msg/domain/admin/repository/CountUserRepository.java
  src/main/java/spharos/msg/domain/admin/service/CountPriceService.java
  src/main/java/spharos/msg/domain/admin/service/CountUserService.java
  src/main/java/spharos/msg/domain/users/controller/AddressController.java
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/entity/UserStatus.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/OAuthServiceImpl.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
Labels: :feather: enhancement

#133 feat: 상품 리뷰 등록,수정,삭제 기능
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/review/controller/ReviewController.java
  src/main/java/spharos/msg/domain/review/entity/Review.java
  src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java
  src/main/java/spharos/msg/domain/review/service/ReviewService.java
Labels: :feather: enhancement

#137 feat : 상품 주문 관련 API 상세 구현 및 order_id 리스트 조회 API 구현
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductOptionResponseDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/orders/controller/OrderController.java
  src/main/java/spharos/msg/domain/orders/dto/OrderRequest.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/entity/OrderProduct.java
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/orders/repository/OrderRepository.java
  src/main/java/spharos/msg/domain/orders/repository/OrderRepositoryCustom.java
  src/main/java/spharos/msg/domain/orders/repository/impl/OrderRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/product/entity/ProductOption.java
  src/main/java/spharos/msg/domain/product/service/ProductOptionService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#139 Feature : 개별 상품 좋아요 유무 조회 #135
  src/main/java/spharos/msg/domain/likes/controller/LikesController.java
  src/main/java/spharos/msg/domain/likes/dto/IsLikesDto.java
  src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
Labels: :feather: enhancement

#143 feat : 개별 상품 옵션 조회 #142
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
  src/main/java/spharos/msg/domain/options/dto/OptionsResponseDto.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
Labels: :feather: enhancement

#147 refactor : Entity 전체 수정 #145
  src/main/java/spharos/msg/domain/category/entity/Category.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryService.java
  src/main/java/spharos/msg/domain/coupon/entity/Coupon.java
  src/main/java/spharos/msg/domain/options/entity/Options.java
  src/main/java/spharos/msg/domain/orders/entity/OrderProduct.java
  src/main/java/spharos/msg/domain/orders/entity/Orders.java
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/orders/repository/impl/OrderRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/product/entity/DeliveryFeeInfo.java
  src/main/java/spharos/msg/domain/product/entity/ProductDetailImage.java
  src/main/java/spharos/msg/domain/product/entity/ProductImage.java
  src/main/java/spharos/msg/domain/product/entity/ProductOption.java
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/product/repository/DeliveryFeeInfoRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductDetailImageRepository.java
  src/main/java/spharos/msg/domain/review/service/ReviewService.java
  src/main/java/spharos/msg/domain/search/entity/Search.java
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/entity/UserCoupon.java
  src/main/java/spharos/msg/domain/users/service/AddressService.java
  src/main/java/spharos/msg/global/config/SecurityConfig.java
  src/main/java/spharos/msg/global/config/WebConfig.java
  src/main/java/spharos/msg/global/entity/BaseEntity.java
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/category/repository/CategoryProductRepositoryTest.java
Labels: :hammer_and_pick: want

#140 feat : Admin용 사용자 Api 추가
  src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
  src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
  src/main/java/spharos/msg/domain/admin/service/CountUserService.java
  src/main/java/spharos/msg/domain/users/entity/LoginType.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement, :hammer_and_pick: want

#141 feat: 베스트탭의 상품 목록 조회 api 구현
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#158 feat: 상품 상세 조회 api 반환값에 responseTime 추가
  .idea/dataSources.xml
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#164 fix : 상품 좋아요 목록 조회 수정 #144
  src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
Labels: :recycle: refactor

#153 refactor : 검색 API 반환값으로 responseTime 추가 #146
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
Labels: :feather: enhancement, :recycle: refactor

#156 feat : 상품 주문 API를 POST와 GET으로 분리
  src/main/java/spharos/msg/domain/orders/controller/OrderController.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/entity/OrderProduct.java
  src/main/java/spharos/msg/domain/orders/entity/Orders.java
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/orders/repository/OrderRepositoryCustom.java
  src/main/java/spharos/msg/domain/orders/repository/impl/OrderRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
Labels: :feather: enhancement, :recycle: refactor

#157 bug : 실시간 상품 검색 API 검색어 누락 문제 #152
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java
Labels: :bug: bug, :recycle: refactor

#160 feat: admin 페이지 베스트 11 반환 api 구현
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#165 feat : ADMIN 페이지 주문 관련 API 작성#162
  src/main/java/spharos/msg/domain/admin/controller/CountPriceController.java
  src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
  src/main/java/spharos/msg/domain/admin/entity/CountPrice.java
  src/main/java/spharos/msg/domain/admin/repository/CountPriceRepository.java
  src/main/java/spharos/msg/domain/admin/service/CountPriceService.java
  src/main/java/spharos/msg/domain/orders/repository/OrderRepository.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#167 feat: 홈화면 랜덤 상품 반환 api 구현
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepository.java
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#150 want : 배송지 조회 Error response 삭제
  src/main/java/spharos/msg/domain/users/service/AddressService.java
Labels: :hammer_and_pick: want

#173 refactor : 주문 구매 내역 조회시, 옵션이 String의 쌍으로 나오도록 구현 #170
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
Labels: :feather: enhancement, :recycle: refactor

#190 feat: 상품의 배송정보 반환 api 구현
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductDetailReponse.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#196 feat: 상품 상세 조회 api 브랜드id로 내려주기
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :hammer_and_pick: want

#174 fix : 옵션이 없는 상품의 옵션 타입 조회 시 빈 배열 반환 #172
  .idea/.gitignore
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
Labels: :bug: bug

#181 want : 회원 정보 조회 API Response Data 추가
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/dto/response/FindUserInfoOutDto.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
Labels: :hammer_and_pick: want

#195 feat : 브랜드 상세 조회 #193
  src/main/java/spharos/msg/domain/brand/controller/BrandController.java
  src/main/java/spharos/msg/domain/brand/dto/BrandDetailDto.java
  src/main/java/spharos/msg/domain/brand/service/BrandService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#189 fix : 옵션 조회 시 product_option_id 추가로 반환 #185
  src/main/java/spharos/msg/domain/options/dto/OptionsResponseDto.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
  src/main/java/spharos/msg/domain/product/entity/ProductOption.java
Labels: :feather: enhancement, :recycle: refactor

#178 refactor : Order 패키지 리팩토링 #177
  src/main/java/spharos/msg/domain/orders/converter/OrderProductConverter.java
  src/main/java/spharos/msg/domain/orders/converter/OrdersConverter.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/orders/repository/impl/OrderRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/product/converter/ProductSalesInfoConverter.java
  src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java
Labels: :recycle: refactor

#182 refactor : Category 패키지 코드 리팩토링 #179
  src/main/java/spharos/msg/domain/category/converter/CategoryConverter.java
  src/main/java/spharos/msg/domain/category/dto/CategoryResponse.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryService.java
Labels: :recycle: refactor

#184 refactor : Search 패키지 리팩토링 #183
  src/main/java/spharos/msg/domain/search/converter/SearchConverter.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
Labels: :recycle: refactor

#200 feat : 상품 옵션명 조회 #142
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
Labels: :feather: enhancement

#201 feat: product 패키지 리팩토링
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepository.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/converter/ProductConvertor.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement, :recycle: refactor

#209 refactor: Review 패키지 리팩토링
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/orders/repository/OrderProductRepository.java
  src/main/java/spharos/msg/domain/product/converter/ProductSalesInfoConverter.java
  src/main/java/spharos/msg/domain/review/controller/ReviewController.java
  src/main/java/spharos/msg/domain/review/converter/ReviewConverter.java
  src/main/java/spharos/msg/domain/review/service/ReviewService.java
Labels: :feather: enhancement

#208 feat: 번들id로 번들정보 조회 api 구현
  src/main/java/spharos/msg/domain/bundle/controller/BundleController.java
  src/main/java/spharos/msg/domain/bundle/convertor/BundleConvertor.java
  src/main/java/spharos/msg/domain/bundle/dto/BundleResponse.java
  src/main/java/spharos/msg/domain/bundle/service/BundleService.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#215 feat : Admin용 User 검색 기능 구현 #211
  src/main/java/spharos/msg/domain/admin/controller/CountUserController.java
  src/main/java/spharos/msg/domain/admin/converter/AdminConverter.java
  src/main/java/spharos/msg/domain/admin/dto/AdminResponseDto.java
  src/main/java/spharos/msg/domain/admin/service/CountUserService.java
  src/main/java/spharos/msg/domain/admin/service/Impl/CountUserServiceImpl.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/impl/AddressServiceImpl.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#222 fix : localhost:3000 직접 허용 처리
  src/main/java/spharos/msg/global/config/SecurityConfig.java
Labels: :bug: bug

#223 merge
  src/main/java/spharos/msg/global/config/SecurityConfig.java
Labels: :bug: bug

#219 refactor : Users Api V1, V2 분기
  src/main/java/spharos/msg/domain/users/controller/v1/AddressControllerV1.java
  src/main/java/spharos/msg/domain/users/controller/v1/AuthControllerV1.java
  src/main/java/spharos/msg/domain/users/controller/v1/OAuthControllerV1.java
  src/main/java/spharos/msg/domain/users/controller/v1/UsersControllerV1.java
  src/main/java/spharos/msg/domain/users/controller/v2/AddressControllerV2.java
  src/main/java/spharos/msg/domain/users/controller/v2/AuthControllerV2.java
  src/main/java/spharos/msg/domain/users/controller/v2/OAuthControllerV2.java
  src/main/java/spharos/msg/domain/users/controller/v2/UsersControllerV2.java
  src/main/java/spharos/msg/domain/users/service/impl/v1/AddressServiceImplV1.java
  src/main/java/spharos/msg/domain/users/service/impl/v1/AuthServiceImplV1.java
  src/main/java/spharos/msg/domain/users/service/impl/v1/OAuthServiceImplV1.java
  src/main/java/spharos/msg/domain/users/service/impl/v1/UsersServiceImplV1.java
  src/main/java/spharos/msg/domain/users/service/impl/v2/AddressServiceImplV2.java
  src/main/java/spharos/msg/domain/users/service/impl/v2/AuthServiceImplV2.java
  src/main/java/spharos/msg/domain/users/service/impl/v2/OAuthServiceImplV2.java
  src/main/java/spharos/msg/domain/users/service/impl/v2/UsersServiceImplV2.java
  src/main/java/spharos/msg/global/config/SecurityConfig.java
Labels: :recycle: refactor

#227 ci/cd : CQRS를 위한 데이터베이스 Master-Slave 리플리케이션 #206
  .github/workflows/buildWithTest.yml
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/spharos/msg/global/config/RoutingDataSourceConfig.java
  src/main/java/spharos/msg/global/database/DatabaseType.java
  src/main/java/spharos/msg/global/database/DynamicRoutingDataSource.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#212 refactor : 장바구니/옵션/좋아요/쿠폰 리팩토링 #176
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/converter/CartConverter.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductOptionResponseDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/cart/service/CartProductUpdateService.java
  src/main/java/spharos/msg/domain/coupon/controller/CouponController.java
  src/main/java/spharos/msg/domain/coupon/service/CouponService.java
  src/main/java/spharos/msg/domain/likes/controller/LikesController.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
  src/main/java/spharos/msg/domain/options/controller/OptionsController.java
  src/main/java/spharos/msg/domain/options/converter/OptionsConverter.java
  src/main/java/spharos/msg/domain/options/dto/OptionsResponseDto.java
  src/main/java/spharos/msg/domain/options/service/OptionsService.java
Labels: :recycle: refactor

#229 refactor : 브랜드 관련 api 성능 개선#226
  src/main/java/spharos/msg/domain/brand/controller/BrandControllerV1.java
  src/main/java/spharos/msg/domain/brand/controller/BrandControllerV2.java
  src/main/java/spharos/msg/domain/brand/dto/BrandDetailDto.java
  src/main/java/spharos/msg/domain/brand/dto/BrandResponseDto.java
  src/main/java/spharos/msg/domain/brand/repository/BrandRepository.java
  src/main/java/spharos/msg/domain/brand/service/BrandServiceV1.java
  src/main/java/spharos/msg/domain/brand/service/BrandServiceV2.java
Labels: :recycle: refactor

#203 chore : Security 인증 경로 상세 지정
  .idea/dataSources.xml
  src/main/java/spharos/msg/global/config/SecurityConfig.java
Labels: :hammer_and_pick: want

#231 refactor : 옵션 패키지 성능 개선 #213
  src/main/java/spharos/msg/domain/options/controller/OptionsControllerV1.java
  src/main/java/spharos/msg/domain/options/controller/OptionsControllerV2.java
  src/main/java/spharos/msg/domain/options/converter/OptionsConverter.java
  src/main/java/spharos/msg/domain/options/dto/OptionTypeDto.java
  src/main/java/spharos/msg/domain/options/dto/OptionsNameDto.java
  src/main/java/spharos/msg/domain/options/repository/OptionsRepository.java
  src/main/java/spharos/msg/domain/options/service/OptionsServiceV1.java
  src/main/java/spharos/msg/domain/options/service/OptionsServiceV2.java
  src/main/java/spharos/msg/domain/orders/service/OrderProductService.java
  src/main/java/spharos/msg/domain/product/repository/ProductOptionRepository.java
Labels: :feather: enhancement, :recycle: refactor

#234 refactor : Search 관련 API 성능 최적화
  src/main/java/spharos/msg/domain/search/controller/SearchControllerV1.java
  src/main/java/spharos/msg/domain/search/controller/SearchControllerV2.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchServiceV1.java
  src/main/java/spharos/msg/domain/search/service/SearchServiceV2.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceV1Test.java
Labels: :recycle: refactor

#233 refactor: Product 패키지 성능 최적화
  src/main/java/spharos/msg/domain/category/controller/CategoryController.java
  src/main/java/spharos/msg/domain/category/entity/CategoryProduct.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepository.java
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/category/service/CategoryServiceV1.java
  src/main/java/spharos/msg/domain/category/service/CategoryServiceV2.java
  src/main/java/spharos/msg/domain/product/controller/ProductControllerV1.java
  src/main/java/spharos/msg/domain/product/controller/ProductControllerV2.java
  src/main/java/spharos/msg/domain/product/converter/ProductConverter.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/spharos/msg/domain/product/repository/impl/ProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/product/service/ProductServiceV1.java
  src/main/java/spharos/msg/domain/product/service/ProductServiceV2.java
  src/test/java/spharos/msg/domain/category/service/CategoryServiceTest.java
Labels: :recycle: refactor

#237 refactor: 베스트 상품 api와 여러 상품 조회 api 성능 개선
  src/main/java/spharos/msg/domain/category/entity/CategoryProduct.java
  src/main/java/spharos/msg/domain/category/repository/impl/CategoryProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/domain/product/repository/impl/ProductRepositoryCustomImpl.java
  src/main/java/spharos/msg/global/config/SecurityConfig.java
Labels: :recycle: refactor

#240 [WANT] STEP 1) V2 API 적용을 위한 모든 API 분기 처리 진행 #239
  src/main/java/spharos/msg/domain/admin/controller/v1/CountPriceControllerV1.java
  src/main/java/spharos/msg/domain/admin/controller/v2/CountPriceControllerV2.java
  src/main/java/spharos/msg/domain/admin/service/CountPriceServiceV1.java
  src/main/java/spharos/msg/domain/admin/service/CountPriceServiceV2.java
  src/main/java/spharos/msg/domain/brand/controller/BrandControllerV1.java
  src/main/java/spharos/msg/domain/brand/controller/BrandControllerV2.java
  src/main/java/spharos/msg/domain/bundle/controller/BundleControllerV1.java
  src/main/java/spharos/msg/domain/bundle/controller/BundleControllerV2.java
  src/main/java/spharos/msg/domain/bundle/service/BundleServiceV1.java
  src/main/java/spharos/msg/domain/bundle/service/BundleServiceV2.java
  src/main/java/spharos/msg/domain/cart/controller/CartProductControllerV1.java
  src/main/java/spharos/msg/domain/cart/controller/CartProductControllerV2.java
  src/main/java/spharos/msg/domain/cart/service/V1/CartProductServiceV1.java
  src/main/java/spharos/msg/domain/cart/service/V1/CartProductUpdateServiceV1.java
  src/main/java/spharos/msg/domain/cart/service/V2/CartProductServiceV2.java
  src/main/java/spharos/msg/domain/cart/service/V2/CartProductUpdateServiceV2.java
  src/main/java/spharos/msg/domain/category/controller/CategoryControllerV1.java
  src/main/java/spharos/msg/domain/category/controller/CategoryControllerV2.java
  src/main/java/spharos/msg/domain/coupon/controller/CouponControllerV1.java
  src/main/java/spharos/msg/domain/coupon/controller/CouponControllerV2.java
  src/main/java/spharos/msg/domain/coupon/scheduler/CouponScheduler.java
  src/main/java/spharos/msg/domain/coupon/service/CouponServiceV1.java
  src/main/java/spharos/msg/domain/coupon/service/CouponServiceV2.java
  src/main/java/spharos/msg/domain/likes/controller/LikesControllerV1.java
  src/main/java/spharos/msg/domain/likes/controller/LikesControllerV2.java
  src/main/java/spharos/msg/domain/options/controller/OptionsControllerV1.java
  src/main/java/spharos/msg/domain/options/controller/OptionsControllerV2.java
  src/main/java/spharos/msg/domain/orders/controller/OrderControllerV1.java
  src/main/java/spharos/msg/domain/orders/controller/OrderControllerV2.java
  src/main/java/spharos/msg/domain/review/controller/ReviewControllerV1.java
  src/main/java/spharos/msg/domain/review/controller/ReviewControllerV2.java
  src/main/java/spharos/msg/domain/review/service/ReviewServiceV1.java
  src/main/java/spharos/msg/domain/review/service/ReviewServiceV2.java
  src/main/java/spharos/msg/domain/search/controller/SearchControllerV1.java
  src/main/java/spharos/msg/domain/search/controller/SearchControllerV2.java
Labels: :hammer_and_pick: want

#244 Update README.md
  README.md
Labels: :page_facing_up: documentation
