Repository 1-MSG/backend, pull requests merged in 2024-03, with the labels that each got.

#7 feat : api 응답 통일 및 예외처리 핸들링 구현 #1
  src/main/java/spharos/msg/domain/cart/controller/CartController.java
  src/main/java/spharos/msg/global/api/ApiResponse.java
  src/main/java/spharos/msg/global/api/code/BaseCode.java
  src/main/java/spharos/msg/global/api/code/BaseErrorCode.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/example/ExampleController.java
  src/main/java/spharos/msg/global/api/example/ExampleException.java
  src/main/java/spharos/msg/global/api/example/ExampleExceptionHandler.java
  src/main/java/spharos/msg/global/api/example/ExampleResponse.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/config/SwaggerConfig.java
  src/main/java/spharos/msg/global/config/WebConfig.java
  src/main/java/spharos/msg/global/configuration/WebConfig.java
  src/main/java/spharos/msg/global/converter/ExampleConverter.java
  src/main/java/spharos/msg/global/dto/BasicResponseDto.java
  src/main/java/spharos/msg/global/dto/ErrorReasonDto.java
  src/main/java/spharos/msg/global/dto/ReasonDto.java
Labels: :feather: enhancement

#11 Feature/#4
  .idea/dataSources.xml
  build.gradle
  src/main/java/spharos/msg/domain/cart/controller/CartController.java
  src/main/java/spharos/msg/domain/cart/service/CartService.java
  src/main/java/spharos/msg/domain/like/controller/LikeController.java
  src/main/java/spharos/msg/domain/like/entity/Like.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/productlike/controller/ProductLikeController.java
  src/main/java/spharos/msg/domain/productlike/dto/ProductLikeResponseDto.java
  src/main/java/spharos/msg/domain/productlike/entity/ProductLike.java
  src/main/java/spharos/msg/domain/productlike/repository/ProductLikeRepository.java
  src/main/java/spharos/msg/domain/productlike/service/ProductLikeService.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/UserRepository.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#15 fix: 좋아요 등록/삭제 API 분리
  src/main/java/spharos/msg/domain/cart/controller/CartController.java
  src/main/java/spharos/msg/domain/cart/service/CartService.java
  src/main/java/spharos/msg/domain/likes/controller/LikesController.java
  src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
  src/main/java/spharos/msg/domain/likes/entity/Likes.java
  src/main/java/spharos/msg/domain/likes/repository/LikesRepository.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
  src/main/java/spharos/msg/domain/productlike/controller/ProductLikeController.java
  src/main/java/spharos/msg/domain/productlike/dto/ProductLikeResponseDto.java
  src/main/java/spharos/msg/domain/productlike/repository/ProductLikeRepository.java
  src/main/java/spharos/msg/domain/productlike/service/ProductLikeService.java
Labels: :feather: enhancement, :recycle: refactor

#13 fix: 시큐리티 관련 코드 삭제
  src/main/java/spharos/msg/domain/cart/controller/CartController.java
  src/main/java/spharos/msg/domain/cart/service/CartService.java
Labels: :bug: bug

#20 feat : api 응답에 isSuccess 프로퍼티 추가 구현 #19
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
  src/main/java/spharos/msg/global/api/ApiResponse.java
Labels: :feather: enhancement

#18 feat : 통합 회원가입 /로그인 구현 #8
  build.gradle
  src/main/java/spharos/msg/MsgApplication.java
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/dto/LoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/SignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/SignUpResponseDto.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/UsersService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/example/ExampleController.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/api/exception/JwtTokenIsExpired.java
  src/main/java/spharos/msg/global/api/exception/LoginIdNotFoundException.java
  src/main/java/spharos/msg/global/api/exception/LoginPwValidationException.java
  src/main/java/spharos/msg/global/api/exception/SignUpDuplicationException.java
  src/main/java/spharos/msg/global/config/ApplicationConfig.java
  src/main/java/spharos/msg/global/config/SecurityConfiguration.java
  src/main/java/spharos/msg/global/config/WebConfig.java
  src/main/java/spharos/msg/global/security/JwtAuthenticationFilter.java
  src/main/java/spharos/msg/global/security/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#22 feat : 홈 화면 상품목록 조회 #6
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/like/controller/LikeController.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductInfoDto.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponseDto.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
Labels: :feather: enhancement

#27 feat : 장바구니 담기/조회/수정/삭제
  src/main/java/spharos/msg/domain/cart/controller/CartController.java
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductOptionResponseDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductRequestDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartRequestDto.java
  src/main/java/spharos/msg/domain/cart/dto/CartResponseDto.java
  src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
  src/main/java/spharos/msg/domain/cart/repository/CartProductRepository.java
  src/main/java/spharos/msg/domain/cart/repository/CartRepository.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/cart/service/CartService.java
  src/main/java/spharos/msg/domain/product/repository/ProductOptionRepository.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/SecurityConfiguration.java
Labels: :feather: enhancement

#37 feat : Users 테이블 양방향 Mapping 추가 및 Colum 추가
  src/main/java/spharos/msg/domain/users/entity/Users.java
Labels: :feather: enhancement

#30 fix : 좋아요 기능 응답 값 통일
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductResponseDto.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/likes/controller/LikesController.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/exception/ProductNotExistException.java
Labels: :recycle: refactor

#32 feat: 홈화면2: 패션잡화 카테고리 상품 조회
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductInfoDto.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponseDto.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
Labels: :feather: enhancement

#38 feat : 쿠폰 조회/다운/삭제
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/coupon/controller/CouponController.java
  src/main/java/spharos/msg/domain/coupon/dto/CouponResponseDto.java
  src/main/java/spharos/msg/domain/coupon/entity/Coupon.java
  src/main/java/spharos/msg/domain/coupon/repository/CouponRepository.java
  src/main/java/spharos/msg/domain/coupon/scheduler/CouponScheduler.java
  src/main/java/spharos/msg/domain/coupon/service/CouponService.java
  src/main/java/spharos/msg/domain/users/entity/UserCoupon.java
  src/main/java/spharos/msg/domain/users/repository/UsersCouponRepository.java
  src/main/java/spharos/msg/global/api/ApiResponse.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :feather: enhancement

#43 feat : swagger 테스트용 JWT 토큰 발급 기능 추가 #42
  .gitignore
  src/main/java/spharos/msg/global/config/SwaggerConfig.java
Labels: :feather: enhancement

#41 feat : 상품 주문 API 구현 #21
  src/main/java/spharos/msg/domain/orders/controller/OrderController.java
  src/main/java/spharos/msg/domain/orders/dto/OrderRequest.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/entity/Orders.java
  src/main/java/spharos/msg/domain/orders/repository/OrderRepository.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
  src/main/java/spharos/msg/global/api/exception/OrderException.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#46 ci : TestCode 검사용 GitAction 추가 #35
  .github/workflows/buildWithTest.yml
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/test/java/spharos/msg/MsgApplicationTests.java
Labels: :feather: enhancement

#48 feat: 상품 상세 조회
  .idea/dataSources.xml
  .idea/vcs.xml
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductDetailInfoDto.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponseDto.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductSalesInfoRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#51 feat : 유저 로그아웃 구현 및 버그 수정
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/dto/NewAddressRequestDto.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/service/AddressService.java
  src/main/java/spharos/msg/domain/users/service/UsersService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/api/example/ExampleController.java
Labels: :bug: bug, :feather: enhancement

#47 refactor : 장바구니 수정 API 분리
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/dto/CartProductRequestDto.java
  src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/cart/service/CartProductUpdateService.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
Labels: :recycle: refactor

#57 feat : JwtTokenProvider 토큰 검증 로직에 대한 수정
  src/main/java/spharos/msg/domain/users/controller/TokenController.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/security/JwtAuthenticationFilter.java
  src/main/java/spharos/msg/global/security/JwtTokenProvider.java
Labels: :hammer_and_pick: want, :recycle: refactor

#58 feat: 상품 리뷰 등록,수정,삭제 기능
  src/main/java/spharos/msg/domain/product/entity/ProductSalesInfo.java
  src/main/java/spharos/msg/domain/review/controller/ReviewController.java
  src/main/java/spharos/msg/domain/review/dto/ReviewRequest.java
  src/main/java/spharos/msg/domain/review/entity/Review.java
  src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java
  src/main/java/spharos/msg/domain/review/service/ReviewService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: :feather: enhancement

#52 feat : 주문자 조회 API 구현 #21
  src/main/java/spharos/msg/domain/orders/controller/OrderController.java
  src/main/java/spharos/msg/domain/orders/dto/OrderResponse.java
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement

#59 ci : Docker Hub를 통한 CI(Continuous Integration) 구현
  .github/workflows/deploy.yml
  Dockerfile_redis
  Dockerfile_spring
  data/redis.conf
  docker-compose.yml
  src/main/resources/application.yml
Labels: :feather: enhancement

#62 fix : 상품 좋아요 유무 필드삭제/Dto에는 반환
  src/main/java/spharos/msg/domain/likes/dto/LikesResponseDto.java
  src/main/java/spharos/msg/domain/likes/entity/Likes.java
  src/main/java/spharos/msg/domain/likes/service/LikesService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
Labels: :recycle: refactor

#65 feat : 상품 검색 API 구현 #60
  .github/workflows/buildWithTest.yml
  .gitignore
  build.gradle
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/QueryDslConfig.java
  src/test/java/spharos/msg/domain/search/repository/SearchRepositoryTest.java
Labels: :feather: enhancement

#64 feat : 간편 회원(카카오) 회원가입 및 로그인 구현 #54
  src/main/java/spharos/msg/domain/users/controller/TokenController.java
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/dto/KakaoLoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/KakaoSignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/NewAddressRequestDto.java
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/entity/KakaoUsers.java
  src/main/java/spharos/msg/domain/users/entity/UserCoupon.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/AddressRepository.java
  src/main/java/spharos/msg/domain/users/repository/KakaoUsersRepository.java
  src/main/java/spharos/msg/domain/users/repository/UserRepository.java
  src/main/java/spharos/msg/domain/users/repository/UsersCouponRepository.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/KakaoUsersService.java
  src/main/java/spharos/msg/domain/users/service/UsersService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/exception/ExceptionAdvice.java
Labels: :feather: enhancement

#63 feat: 상품 상세 조회
  .idea/dataSources.xml
  src/main/java/spharos/msg/domain/category/repository/CategoryProductRepository.java
  src/main/java/spharos/msg/domain/product/controller/ProductController.java
  src/main/java/spharos/msg/domain/product/dto/ProductDetailInfoDto.java
  src/main/java/spharos/msg/domain/product/dto/ProductDetailReponse.java
  src/main/java/spharos/msg/domain/product/dto/ProductInfoDto.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponse.java
  src/main/java/spharos/msg/domain/product/dto/ProductResponseDto.java
  src/main/java/spharos/msg/domain/product/entity/Product.java
  src/main/java/spharos/msg/domain/product/entity/ProductDetailImage.java
  src/main/java/spharos/msg/domain/product/repository/DeliveryFeeInfoRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductDetailImageRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductImageRepository.java
  src/main/java/spharos/msg/domain/product/repository/ProductRepository.java
  src/main/java/spharos/msg/domain/product/service/ProductService.java
  src/main/java/spharos/msg/domain/review/repository/ReviewImageRepository.java
  src/main/java/spharos/msg/domain/review/repository/ReviewRepository.java
Labels: :feather: enhancement

#72 feat : User Entity userName 반환 메소드 추가
  src/main/java/spharos/msg/domain/users/entity/Users.java
Labels: :feather: enhancement, :hammer_and_pick: want

#73 fix : 장바구니 수정 방식 변경
  src/main/java/spharos/msg/domain/cart/controller/CartProductController.java
  src/main/java/spharos/msg/domain/cart/entity/CartProduct.java
  src/main/java/spharos/msg/domain/cart/service/CartProductService.java
  src/main/java/spharos/msg/domain/cart/service/CartProductUpdateService.java
  src/main/java/spharos/msg/global/entity/BaseEntity.java
Labels: :recycle: refactor

#77 REFACTOR : 회원 API 전체 Refactoring 진행
  build.gradle
  src/main/java/spharos/msg/domain/orders/service/OrderService.java
  src/main/java/spharos/msg/domain/users/controller/AddressController.java
  src/main/java/spharos/msg/domain/users/controller/AuthController.java
  src/main/java/spharos/msg/domain/users/controller/OAuthController.java
  src/main/java/spharos/msg/domain/users/controller/TokenController.java
  src/main/java/spharos/msg/domain/users/controller/UsersController.java
  src/main/java/spharos/msg/domain/users/dto/KakaoLoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/KakaoSignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/NewAddressRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/AddressRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/DuplicationCheckRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EasyLoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EasySignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EmailAuthRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/EmailSendRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/LoginRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/ReissueRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/request/SignUpRequestDto.java
  src/main/java/spharos/msg/domain/users/dto/response/AddressOutDto.java
  src/main/java/spharos/msg/domain/users/dto/response/EasySignUpOutDto.java
  src/main/java/spharos/msg/domain/users/dto/response/EmailOutDto.java
  src/main/java/spharos/msg/domain/users/dto/response/LoginOutDto.java
  src/main/java/spharos/msg/domain/users/dto/response/ReissueOutDto.java
  src/main/java/spharos/msg/domain/users/entity/Address.java
  src/main/java/spharos/msg/domain/users/entity/KakaoUsers.java
  src/main/java/spharos/msg/domain/users/entity/UserOAuthList.java
  src/main/java/spharos/msg/domain/users/entity/Users.java
  src/main/java/spharos/msg/domain/users/repository/KakaoUsersRepository.java
  src/main/java/spharos/msg/domain/users/repository/UserOAuthListRepository.java
  src/main/java/spharos/msg/domain/users/repository/UsersRepository.java
  src/main/java/spharos/msg/domain/users/service/AddressService.java
  src/main/java/spharos/msg/domain/users/service/AuthService.java
  src/main/java/spharos/msg/domain/users/service/AuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/KakaoUsersService.java
  src/main/java/spharos/msg/domain/users/service/OAuthService.java
  src/main/java/spharos/msg/domain/users/service/OAuthServiceImpl.java
  src/main/java/spharos/msg/domain/users/service/UsersService.java
  src/main/java/spharos/msg/global/api/code/status/ErrorStatus.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/CorsConfig.java
  src/main/java/spharos/msg/global/config/EmailConfig.java
  src/main/java/spharos/msg/global/config/SecurityConfiguration.java
  src/main/java/spharos/msg/global/redis/RedisService.java
  src/main/java/spharos/msg/global/security/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/orders/service/OrderServiceTest.java
Labels: :feather: enhancement, :recycle: refactor

#75 feat : 상품검색 API 구현 #60
  src/main/java/spharos/msg/domain/search/controller/SearchController.java
  src/main/java/spharos/msg/domain/search/dto/SearchResponse.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepository.java
  src/main/java/spharos/msg/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/spharos/msg/domain/search/service/SearchService.java
  src/main/java/spharos/msg/global/api/code/status/SuccessStatus.java
  src/main/java/spharos/msg/global/config/SecurityConfiguration.java
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/search/repository/SearchRepositoryTest.java
  src/test/java/spharos/msg/domain/search/service/SearchServiceTest.java
Labels: :feather: enhancement

#80 fix : JPA Redis Repository scan 문제 해결
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/users/service/UsersServiceTest.java
Labels: :bug: bug

#89 Revert : "fix : JPA Redis Repository scan 문제 해결"
  .github/workflows/deploy.yml
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/users/service/UsersServiceTest.java
Labels: :bug: bug

#90 Revert : "fix : JPA Redis Repository scan 문제 해결"
  src/main/resources/application.yml
  src/test/java/spharos/msg/domain/users/service/UsersServiceTest.java
Labels: :bug: bug
